/** Generated by YAKINDU Statechart Tools code generator. */
package dwatch.digitalwatch;

import dwatch.ITimer;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;

public class DigitalwatchStatemachine implements IDigitalwatchStatemachine {
	protected class SCIButtonsImpl implements SCIButtons {
	
		private boolean topLeftPressed;
		
		
		public synchronized void raiseTopLeftPressed() {
			topLeftPressed = true;
			runCycle();
		}
		
		private boolean topLeftReleased;
		
		
		public synchronized void raiseTopLeftReleased() {
			topLeftReleased = true;
			runCycle();
		}
		
		private boolean topRightPressed;
		
		
		public synchronized void raiseTopRightPressed() {
			topRightPressed = true;
			runCycle();
		}
		
		private boolean topRightReleased;
		
		
		public synchronized void raiseTopRightReleased() {
			topRightReleased = true;
			runCycle();
		}
		
		private boolean botLeftPressed;
		
		
		public synchronized void raiseBotLeftPressed() {
			botLeftPressed = true;
			runCycle();
		}
		
		private boolean botLeftReleased;
		
		
		public synchronized void raiseBotLeftReleased() {
			botLeftReleased = true;
			runCycle();
		}
		
		private boolean botRightPressed;
		
		
		public synchronized void raiseBotRightPressed() {
			botRightPressed = true;
			runCycle();
		}
		
		private boolean botRightReleased;
		
		
		public synchronized void raiseBotRightReleased() {
			botRightReleased = true;
			runCycle();
		}
		
		protected void clearEvents() {
			topLeftPressed = false;
			topLeftReleased = false;
			topRightPressed = false;
			topRightReleased = false;
			botLeftPressed = false;
			botLeftReleased = false;
			botRightPressed = false;
			botRightReleased = false;
		}
	}
	
	
	protected class SCIDisplayImpl implements SCIDisplay {
	
		private SCIDisplayOperationCallback operationCallback;
		
		public synchronized void setSCIDisplayOperationCallback(
				SCIDisplayOperationCallback operationCallback) {
			this.operationCallback = operationCallback;
		}
	}
	
	
	protected class SCILogicUnitImpl implements SCILogicUnit {
	
		private SCILogicUnitOperationCallback operationCallback;
		
		public synchronized void setSCILogicUnitOperationCallback(
				SCILogicUnitOperationCallback operationCallback) {
			this.operationCallback = operationCallback;
		}
	}
	
	
	protected SCIButtonsImpl sCIButtons;
	
	protected SCIDisplayImpl sCIDisplay;
	
	protected SCILogicUnitImpl sCILogicUnit;
	
	private boolean initialized = false;
	
	public enum State {
		main_region_Dead,
		main_region_Alive,
		main_region_Digital_Watch,
		main_region_Digital_Watch_sub_region_Time_Mode,
		$NullState$
	};
	
	private final State[] stateVector = new State[1];
	
	private int nextStateIndex;
	
	private ITimer timer;
	
	private final boolean[] timeEvents = new boolean[4];
	
	private long n;
	
	protected long getN() {
		return n;
	}
	
	protected void setN(long value) {
		this.n = value;
	}
	
	
	private boolean topRightPressed;
	
	protected boolean getTopRightPressed() {
		return topRightPressed;
	}
	
	protected void setTopRightPressed(boolean value) {
		this.topRightPressed = value;
	}
	
	
	private long lightsOffCounter;
	
	protected long getLightsOffCounter() {
		return lightsOffCounter;
	}
	
	protected void setLightsOffCounter(long value) {
		this.lightsOffCounter = value;
	}
	
	
	public DigitalwatchStatemachine() {
		sCIButtons = new SCIButtonsImpl();
		sCIDisplay = new SCIDisplayImpl();
		sCILogicUnit = new SCILogicUnitImpl();
	}
	
	public synchronized void init() {
		this.initialized = true;
		if (timer == null) {
			throw new IllegalStateException("timer not set.");
		}
		if (this.sCIDisplay.operationCallback == null) {
			throw new IllegalStateException("Operation callback for interface sCIDisplay must be set.");
		}
		
		if (this.sCILogicUnit.operationCallback == null) {
			throw new IllegalStateException("Operation callback for interface sCILogicUnit must be set.");
		}
		
		for (int i = 0; i < 1; i++) {
			stateVector[i] = State.$NullState$;
		}
		clearEvents();
		clearOutEvents();
		setN(0);
		
		setTopRightPressed(false);
		
		setLightsOffCounter(2000);
	}
	
	public synchronized void enter() {
		if (!initialized) {
			throw new IllegalStateException(
				"The state machine needs to be initialized first by calling the init() function."
			);
		}
		if (timer == null) {
			throw new IllegalStateException("timer not set.");
		}
		enterSequence_main_region_default();
	}
	
	public synchronized void runCycle() {
		if (!initialized)
			throw new IllegalStateException(
					"The state machine needs to be initialized first by calling the init() function.");
		clearOutEvents();
		for (nextStateIndex = 0; nextStateIndex < stateVector.length; nextStateIndex++) {
			switch (stateVector[nextStateIndex]) {
			case main_region_Dead:
				main_region_Dead_react(true);
				break;
			case main_region_Alive:
				main_region_Alive_react(true);
				break;
			case main_region_Digital_Watch_sub_region_Time_Mode:
				main_region_Digital_Watch_sub_region_Time_Mode_react(true);
				break;
			default:
				// $NullState$
			}
		}
		clearEvents();
	}
	public synchronized void exit() {
		exitSequence_main_region();
	}
	
	/**
	 * @see IStatemachine#isActive()
	 */
	public synchronized boolean isActive() {
		return stateVector[0] != State.$NullState$;
	}
	
	/** 
	* Always returns 'false' since this state machine can never become final.
	*
	* @see IStatemachine#isFinal()
	*/
	public synchronized boolean isFinal() {
		return false;
	}
	/**
	* This method resets the incoming events (time events included).
	*/
	protected void clearEvents() {
		sCIButtons.clearEvents();
		for (int i=0; i<timeEvents.length; i++) {
			timeEvents[i] = false;
		}
	}
	
	/**
	* This method resets the outgoing events.
	*/
	protected void clearOutEvents() {
	}
	
	/**
	* Returns true if the given state is currently active otherwise false.
	*/
	public synchronized boolean isStateActive(State state) {
	
		switch (state) {
		case main_region_Dead:
			return stateVector[0] == State.main_region_Dead;
		case main_region_Alive:
			return stateVector[0] == State.main_region_Alive;
		case main_region_Digital_Watch:
			return stateVector[0].ordinal() >= State.
					main_region_Digital_Watch.ordinal()&& stateVector[0].ordinal() <= State.main_region_Digital_Watch_sub_region_Time_Mode.ordinal();
		case main_region_Digital_Watch_sub_region_Time_Mode:
			return stateVector[0] == State.main_region_Digital_Watch_sub_region_Time_Mode;
		default:
			return false;
		}
	}
	
	/**
	* Set the {@link ITimer} for the state machine. It must be set
	* externally on a timed state machine before a run cycle can be correctly
	* executed.
	* 
	* @param timer
	*/
	public synchronized void setTimer(ITimer timer) {
		this.timer = timer;
	}
	
	/**
	* Returns the currently used timer.
	* 
	* @return {@link ITimer}
	*/
	public ITimer getTimer() {
		return timer;
	}
	
	public synchronized void timeElapsed(int eventID) {
		timeEvents[eventID] = true;
		runCycle();
	}
	
	public SCIButtons getSCIButtons() {
		return sCIButtons;
	}
	
	public SCIDisplay getSCIDisplay() {
		return sCIDisplay;
	}
	
	public SCILogicUnit getSCILogicUnit() {
		return sCILogicUnit;
	}
	
	/* Entry action for state 'Dead'. */
	private void entryAction_main_region_Dead() {
		timer.setTimer(this, 0, 200, false);
		
		sCIDisplay.operationCallback.refreshTimeDisplay();
		
		sCIDisplay.operationCallback.unsetIndiglo();
	}
	
	/* Entry action for state 'Alive'. */
	private void entryAction_main_region_Alive() {
		timer.setTimer(this, 1, 200, false);
		
		sCIDisplay.operationCallback.setIndiglo();
		
		sCILogicUnit.operationCallback.increaseTimeByOne();
		
		sCIDisplay.operationCallback.hidePos(getN());
		
		setN((((n + 1)) % 6));
	}
	
	/* Entry action for state 'Digital Watch'. */
	private void entryAction_main_region_Digital_Watch() {
		timer.setTimer(this, 2, (1 * 1000), true);
		
		sCIDisplay.operationCallback.refreshDateDisplay();
	}
	
	/* Entry action for state 'Time Mode'. */
	private void entryAction_main_region_Digital_Watch_sub_region_Time_Mode() {
		timer.setTimer(this, 3, (1 * 1000), true);
		
		sCIDisplay.operationCallback.refreshTimeDisplay();
	}
	
	/* Exit action for state 'Dead'. */
	private void exitAction_main_region_Dead() {
		timer.unsetTimer(this, 0);
	}
	
	/* Exit action for state 'Alive'. */
	private void exitAction_main_region_Alive() {
		timer.unsetTimer(this, 1);
	}
	
	/* Exit action for state 'Digital Watch'. */
	private void exitAction_main_region_Digital_Watch() {
		timer.unsetTimer(this, 2);
	}
	
	/* Exit action for state 'Time Mode'. */
	private void exitAction_main_region_Digital_Watch_sub_region_Time_Mode() {
		timer.unsetTimer(this, 3);
	}
	
	/* 'default' enter sequence for state Dead */
	private void enterSequence_main_region_Dead_default() {
		entryAction_main_region_Dead();
		nextStateIndex = 0;
		stateVector[0] = State.main_region_Dead;
	}
	
	/* 'default' enter sequence for state Alive */
	private void enterSequence_main_region_Alive_default() {
		entryAction_main_region_Alive();
		nextStateIndex = 0;
		stateVector[0] = State.main_region_Alive;
	}
	
	/* 'default' enter sequence for state Digital Watch */
	private void enterSequence_main_region_Digital_Watch_default() {
		entryAction_main_region_Digital_Watch();
		enterSequence_main_region_Digital_Watch_sub_region_default();
	}
	
	/* 'default' enter sequence for state Time Mode */
	private void enterSequence_main_region_Digital_Watch_sub_region_Time_Mode_default() {
		entryAction_main_region_Digital_Watch_sub_region_Time_Mode();
		nextStateIndex = 0;
		stateVector[0] = State.main_region_Digital_Watch_sub_region_Time_Mode;
	}
	
	/* 'default' enter sequence for region main region */
	private void enterSequence_main_region_default() {
		react_main_region__entry_Default();
	}
	
	/* 'default' enter sequence for region sub region */
	private void enterSequence_main_region_Digital_Watch_sub_region_default() {
		react_main_region_Digital_Watch_sub_region__entry_Default();
	}
	
	/* Default exit sequence for state Dead */
	private void exitSequence_main_region_Dead() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
		
		exitAction_main_region_Dead();
	}
	
	/* Default exit sequence for state Alive */
	private void exitSequence_main_region_Alive() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
		
		exitAction_main_region_Alive();
	}
	
	/* Default exit sequence for state Time Mode */
	private void exitSequence_main_region_Digital_Watch_sub_region_Time_Mode() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
		
		exitAction_main_region_Digital_Watch_sub_region_Time_Mode();
	}
	
	/* Default exit sequence for region main region */
	private void exitSequence_main_region() {
		switch (stateVector[0]) {
		case main_region_Dead:
			exitSequence_main_region_Dead();
			break;
		case main_region_Alive:
			exitSequence_main_region_Alive();
			break;
		case main_region_Digital_Watch_sub_region_Time_Mode:
			exitSequence_main_region_Digital_Watch_sub_region_Time_Mode();
			exitAction_main_region_Digital_Watch();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region sub region */
	private void exitSequence_main_region_Digital_Watch_sub_region() {
		switch (stateVector[0]) {
		case main_region_Digital_Watch_sub_region_Time_Mode:
			exitSequence_main_region_Digital_Watch_sub_region_Time_Mode();
			break;
		default:
			break;
		}
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region__entry_Default() {
		enterSequence_main_region_Digital_Watch_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_Digital_Watch_sub_region__entry_Default() {
		enterSequence_main_region_Digital_Watch_sub_region_Time_Mode_default();
	}
	
	private boolean react() {
		return false;
	}
	
	private boolean main_region_Dead_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (react()==false) {
				if (timeEvents[0]) {
					exitSequence_main_region_Dead();
					enterSequence_main_region_Alive_default();
				} else {
					did_transition = false;
				}
			}
		}
		return did_transition;
	}
	
	private boolean main_region_Alive_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (react()==false) {
				if (timeEvents[1]) {
					exitSequence_main_region_Alive();
					enterSequence_main_region_Dead_default();
				} else {
					did_transition = false;
				}
			}
		}
		return did_transition;
	}
	
	private boolean main_region_Digital_Watch_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (react()==false) {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			if (timeEvents[2]) {
				sCILogicUnit.operationCallback.increaseTimeByOne();
				
				sCIDisplay.operationCallback.refreshTimeDisplay();
			}
			if (sCIButtons.topRightPressed) {
				sCIDisplay.operationCallback.setIndiglo();
				
				setTopRightPressed(true);
			}
			if (sCIButtons.topRightReleased) {
				setTopRightPressed(false);
				
				setLightsOffCounter(2000);
			}
		}
		return did_transition;
	}
	
	private boolean main_region_Digital_Watch_sub_region_Time_Mode_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (main_region_Digital_Watch_react(try_transition)==false) {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			if (timeEvents[3]) {
				sCIDisplay.operationCallback.refreshTimeDisplay();
			}
		}
		return did_transition;
	}
	
}
